//@ui5-bundle zza/zza/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"zza/zza/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","zza/zza/model/models"],function(e,t,i){"use strict";return e.extend("zza.zza.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"zza/zza/controller/View1.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/m/MessageBox"],function(e,o){"use strict";return e.extend("zza.zza.controller.View1",{onInit:function(){},onPress:function(e){debugger;var r={RequestId:"CAPEX_REQ_00_000",Title:"Build mobile apps",productId:"2",Requester:{Name:"John Dilbert",Email:"john.dilbert@saptest.com",UserId:"P000000",Comment:"Please approve the capital expenditure"},Investment:{TotalCost:1e4,Type:"Software",CAPEX:1e4,OPEX:4e3,Division:"BPM",ROI:5,Country:"Germany",Currency:"EUR",Description:"Provide a fresh experience for our customers by providing new apps for our services"},rulesRequest:{RuleServiceId:"9ea8faaf6a3d41adac2b791a92303532",Vocabulary:[{Employee:{IsFullTimeEmployee:true,countryofCompany:"USA",jobTitle:"Engineer II",company:"2000"}}]},workflowRequest:{definitionId:"bpm_wf_fall_001",context:{}}};var n="bpm_wf_001";var t={definitionId:n,context:r};$.ajax({url:"/zzazza/bpmworkflowruntime/v1/xsrf-token",method:"GET",headers:{"X-CSRF-Token":"Fetch"},success:function(e,r,n){var a=n.getResponseHeader("X-CSRF-Token");if(a===null)return;debugger;$.ajax({url:"/zzazza/bpmworkflowruntime/v1/workflow-instances",type:"POST",data:JSON.stringify(t),headers:{"X-CSRF-Token":a,"Content-Type":"application/json"},async:false,success:function(e){o.success("workflow call successfull")},Error:function(e){o.error("workflow call failed")}})}})}})});
},
	"zza/zza/i18n/i18n.properties":'title=Title\nappTitle=zza\nappDescription=App Description',
	"zza/zza/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"zza.zza","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","sourceTemplate":{"id":"html5moduletemplates.basicSAPUI5ApplicationProjectModule","version":"1.40.12"},"dataSources":{"mainService":{"uri":"V2/Northwind/Northwind.svc/","type":"OData","settings":{"odataVersion":"2.0","localUri":"localService/metadata.xml"}}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"zza.zza.view.View1","type":"XML","async":true,"id":"View1"},"dependencies":{"minUI5Version":"1.65.6","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"zza.zza.i18n.i18n"}},"":{"dataSource":"mainService","preload":true,"settings":{"defaultBindingMode":"TwoWay","defaultCountMode":"Inline","refreshAfterChange":false}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"zza.zza.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteView1","pattern":"RouteView1","target":["TargetView1"]}],"targets":{"TargetView1":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"View1","viewName":"View1"}}}}}',
	"zza/zza/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"zza/zza/view/View1.view.xml":'<mvc:View controllerName="zza.zza.controller.View1" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m"><Shell id="shell"><App id="app"><pages><Page id="page" title="{i18n>title}"><content><Button text="Start" type="Emphasized" press=".onPress"/><List items="{/Products}"><StandardListItem title="{ProductName}" description="{ProductID}" info="{QuantityPerUnit}"/></List></content></Page></pages></App></Shell></mvc:View>'
}});
