//@ui5-bundle zabfall/zabfall/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"zabfall/zabfall/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","zabfall/zabfall/model/models"],function(e,t,a){"use strict";return e.extend("zabfall.zabfall.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(a.createDeviceModel(),"device");debugger;if(this.getComponentData()){var t=this.getComponentData().startupParameters;if(t){var o=t.taskModel;var s=o.getData();var i=s.InstanceID}}var n=new sap.ui.model.json.JSONModel;n.setProperty("/taskId",i);this.setModel(n,"ctaskModel");var r=this;$.ajax({type:"GET",url:"/zabfallzabfall/bpmworkflowruntime/v1/task-instances/"+i+"/context",success:function(e){var t=r.getModel("ctaskModel");t.setProperty("/context",e)},error:function(e,t){}})}})});
},
	"zabfall/zabfall/controller/home.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("zabfall.zabfall.controller.home",{onInit:function(){var e=this.getOwnerComponent().getModel("ctaskModel");this.getView().setModel(e,"contextModel")},onCancelRun:function(e){var t=this.getOwnerComponent().getModel("ctaskModel");var n=t.getProperty("/taskId");var a=this;var o={status:"COMPLETED"};$.ajax({url:"/zabfallzabfall/bpmworkflowruntime/v1/xsrf-token",method:"GET",headers:{"X-CSRF-Token":"Fetch"},success:function(e,t,r){var s=r.getResponseHeader("X-CSRF-Token");if(s===null)return;$.ajax({url:"/zabfallzabfall/bpmworkflowruntime/v1/task-instances/"+n,type:"PATCH",data:JSON.stringify(o),headers:{"X-CSRF-Token":s,"Content-Type":"application/json"},async:false,success:function(e){a.getOwnerComponent().getComponentData().startupParameters.inboxAPI.updateTask("NA",n)},Error:function(e){}})}})},onReporcess:function(e){var t=this.getOwnerComponent().getModel("ctaskModel");var n=t.getProperty("/taskId");var a=this;var o={status:"COMPLETED",context:{productId:a.getView().getModel("ctaskModel").getProperty("/context/productId")}};$.ajax({url:"/zabfallzabfall/bpmworkflowruntime/v1/xsrf-token",method:"GET",headers:{"X-CSRF-Token":"Fetch"},success:function(e,t,r){var s=r.getResponseHeader("X-CSRF-Token");if(s===null)return;$.ajax({url:"/zabfallzabfall/bpmworkflowruntime/v1/task-instances/"+n,type:"PATCH",data:JSON.stringify(o),headers:{"X-CSRF-Token":s,"Content-Type":"application/json"},async:false,success:function(e){a.getOwnerComponent().getComponentData().startupParameters.inboxAPI.updateTask("NA",n)},Error:function(e){}})}})}})});
},
	"zabfall/zabfall/i18n/i18n.properties":'title=Title\nappTitle=zabfall\nappDescription=App Description',
	"zabfall/zabfall/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"zabfall.zabfall","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","crossNavigation":{"inbounds":{"intent1":{"signature":{"parameters":{},"additionalParameters":"allowed"},"semanticObject":"Fallout","action":"display","title":"fallout","icon":"sap-icon://add"}}},"sourceTemplate":{"id":"html5moduletemplates.basicSAPUI5ApplicationProjectModule","version":"1.40.12"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"zabfall.zabfall.view.home","type":"XML","async":true,"id":"home"},"dependencies":{"minUI5Version":"1.65.6","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"zabfall.zabfall.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"zabfall.zabfall.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"Routehome","pattern":"Routehome","target":["Targethome"]}],"targets":{"Targethome":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"home","viewName":"home"}}}}}',
	"zabfall/zabfall/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"zabfall/zabfall/view/home.view.xml":'<mvc:View controllerName="zabfall.zabfall.controller.home" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m" height="100%"><Page id="page" title="Fallour Message"><content><Label text="Product Id" labelFor="idInput"/><Input id="idInput" value="{contextModel>/context/productId}"/></content><footer><OverflowToolbar class="sapContrast sapContrastPlus" width="100%" id="toolbar3"><content><ToolbarSpacer id="spacer2"/><Button icon="sap-icon://cancel" iconFirst="false" id="button6" type="Reject" text="Cancel Run" press=".onCancelRun"/><Button icon="sap-icon://refresh" iconFirst="false"  id="button5" type="Accept" text="Reprocess" press=".onReporcess"/></content></OverflowToolbar></footer></Page></mvc:View>'
}});
